name:                mgit
version:             0.1.0.0
github:              "zxc123zxc/mgit"
license:             BSD3
author:              "Author name here"
maintainer:          "Author email here"
copyright:           "2019 Author name here"
synopsis:            Multi-repo git tool
category:            git, tools
description:         Please see the README on GitHub at <https://github.com/zxc123zxc/mgit#readme>

extra-libraries:
  - git2                # libgit2 @ 0.28.3  (https://libgit2.org/)

extra-source-files:
  - README.md
  - ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- mtl                   # monad transformers
- array                 # old lib for arrays
- vector                # arrays
- optparse-applicative  # args parser
- directory             # working with dirs. CurrentDir
- system-fileio         # advanced working with paths
- system-filepath
- text                  # overloading strings
- bytestring            # overloading byte strings
- c-storable-deriving   # Storable deriving for C lang
- time
- tagged
- process

library:
  source-dirs: src
  c-sources:
    - cbits/test_ffi.c
    - cbits/git_integr.c
  include-dirs:
    include

executables:
  mgit-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mgit

tests:
  mgit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mgit
